Fix lasagna test error (missing parens in test file)
Lasagna is failing me, though I correctly stacked all the layers.

Local swift version is 5.5.1-dev, but it also fails on exercism: https://exercism.org/tracks/swift/exercises/lasagna/iterations?idx=1

```
<path>/exercism/swift/lasagna/Tests/LasagnaTests/LasagnaTests.swift:8:20: error: add () to forward @autoclosure parameter
    XCTAssertEqual(expectedMinutesInOven, 40) // !!
                   ^~~~~~~~~~~~~~~~~~~~~
                                        ()
[1/2] Compiling LasagnaTests LasagnaTests.swift
error: fatalError
```